### PR TITLE
Update dependencies, builds with ghc 9.2.2

### PR DESCRIPTION
**Pull request by fgaz**
Tested by running
cabal build --constraint optparse-applicative==0.17.0.0 --constraint cabal-install-parsers==0.4.5 --constraint Cabal==3.6.3.0 --constraint bytestring==0.11.3.0 --constraint base==4.16.1.0

### CODE REVIEW

**Comment by fgaz** [comment]
Ping

**Comment by fgaz** [comment]
@phadej is this still maintained?

**Comment by Mikolaj** [comment]
Ping, ping! :)

**Comment by phadej** [comment]
I don't use nor work on `changelog-d` myself anymore. Feel free to fork. I can also transfer the repository to someone if that is valuabe.

**Comment by Mikolaj** [comment]
@phadej: yes, it's a pity to leave such a usable tool unmaintained and/or forked, so it'd be great to give it a new maintainer. @fgaz graciously offered to take over. If that's fine, how do we proceed?

**Comment by phadej** [comment]
I can transfer this repository but `fgaz/changelog-d already exists`.

That said, there's nothing bad in forking. This package is not released anywhere, I don't need to transfer any "rights", you can just start using different repository than this one.

**Comment by fgaz** [comment]
Indeed it looks like there is no extra metadata like issues that needs moving. Fork it is then. Thanks for your work on this tool, @phadej 

edit: the fork now lives at https://github.com/fgaz/changelog-d

**Comment by Mikolaj** [comment]
@phadej, @fgaz: thank you!

**Comment by phadej** [comment]
There's also https://github.com/nedbat/scriv

**Comment by ulysses4ever** [comment]
From Scriv’s readme:

> To make a new changelog fragment, use the `scriv create`command. It will make a new file with a filename using the current date and time, your GitHub or Git user name, 

so, every contributor needs to install it, which I dislike. I guess, it can be avoided by manually creating the file, just like we do now with changelog-d. I didn’t check their format, and so can’t say how easy it is.

otoh, I love that git name / GitHub handle is a part of the format: I think our release notes (which get contents of changelogs) should absolutely credit the contributors.

**Comment by fgaz** [comment]
I think the most complete one is https://changie.dev/

It almost covers all changelog-d features. A major omission is changelog-d's `--prlog`

**Pull request closed without merging**
